base: /
dependencies:
  - 'site-distribution/main'
languages:
  -
    title: English
    enabled: true
    languageId: 0
    base: /
    locale: en_US.UTF-8
    navigationTitle: English
    direction: ''
    flag: us

rootPageId: 1
websiteTitle: 'TYPO3 Site Distribution'
errorHandling:
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: 't3://page?uid=4'
routeEnhancers:
  -
    type: PageType
    default: '/'
    index: ''
    map:
      /: 0
      sitemap.xml: 1533906435
