seo:
  sitemap:
    pages:
      # Exclude 404 page from sitemap
      excludePagesRecursive: '4'
styles:
  templates:
    # To override the default templates, place your fluid files with the same filenames in the defined directories
    templateRootPath: 'EXT:site-distribution/Resources/Private/Templates/Content'
    partialRootPath: 'EXT:site-distribution/Resources/Private/Partials/Content'
    layoutRootPath: 'EXT:site-distribution/Resources/Private/Layouts/Content'
